# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Efe\Documents\GitHub\Gorsel Programlama Efe\8.Hafta 2\__pycache__\soruekle2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SoruEkleme(object):
    def setupUi(self, SoruEkleme):
        SoruEkleme.setObjectName("SoruEkleme")
        SoruEkleme.resize(800, 490)
        self.verticalLayout = QtWidgets.QVBoxLayout(SoruEkleme)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableQuestions = QtWidgets.QTableWidget(SoruEkleme)
        self.tableQuestions.setObjectName("tableQuestions")
        self.tableQuestions.setColumnCount(6)
        self.tableQuestions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableQuestions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableQuestions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableQuestions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableQuestions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableQuestions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableQuestions.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableQuestions)
        self.pushButton = QtWidgets.QPushButton(SoruEkleme)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(SoruEkleme)
        QtCore.QMetaObject.connectSlotsByName(SoruEkleme)

    def retranslateUi(self, SoruEkleme):
        _translate = QtCore.QCoreApplication.translate
        SoruEkleme.setWindowTitle(_translate("SoruEkleme", "Soru Ekleme"))
        item = self.tableQuestions.horizontalHeaderItem(0)
        item.setText(_translate("SoruEkleme", "Soru"))
        item = self.tableQuestions.horizontalHeaderItem(1)
        item.setText(_translate("SoruEkleme", "A"))
        item = self.tableQuestions.horizontalHeaderItem(2)
        item.setText(_translate("SoruEkleme", "B"))
        item = self.tableQuestions.horizontalHeaderItem(3)
        item.setText(_translate("SoruEkleme", "C"))
        item = self.tableQuestions.horizontalHeaderItem(4)
        item.setText(_translate("SoruEkleme", "D"))
        item = self.tableQuestions.horizontalHeaderItem(5)
        item.setText(_translate("SoruEkleme", "E"))
        self.pushButton.setText(_translate("SoruEkleme", "Yazdır"))
